FROM nginx:1.22-alpine

WORKDIR /usr/src/

COPY . .

RUN apk add --update npm &&\
    npm ci &&\
    npm run build &&\
    rm -rf /usr/share/nginx/html/* &&\
    mv -f ./dist/client/* /usr/share/nginx/html &&\
    rm -r ./dist
