version: '3.9'

services:
  database:
    container_name: database
    image: postgres:alpine3.16
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
  server:
    container_name: server
    build: ./server
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
      - POSTGRES_ADDR=database
      - JWT_KEY=my_secret_key
    ports:
      - "8080:8080"
  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    ports:
      - "4200:80"
