version: '3.9'

services:
  database:
    container_name: database
    image: postgres:alpine3.16
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5005:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
  # server:
  #   depends_on:
  #     - database
  # client:
  #   depends_on:
  #     - server
    
